- shell:
    - zsh/set-default-shell.sh
- link:
    ~/.zshenv: zsh/zshenv
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc
    ~/.zlogin: zsh/zlogin
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprezto: zsh/prezto/
