set nocompatible              " be iMproved, required

if has("autocmd")
        filetype plugin indent on
endif

if has('syntax')
        syntax enable
endif

set autoindent
set smarttab
set ruler
set wildmenu
set expandtab
set cursorline
set number

packloadall

" fix backspacing
fixdel
set backspace=indent,eol,start

"jsx stuff
let g:jsx_ext_required = 0
"prettier stuff
let g:prettier#autoformat_require_pragma = 0

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

if (has("termguicolors"))
 set termguicolors
endif

colorscheme night-owl
